package EMIRDFAGENT;


/**
* EMIRDFAGENT/EMIRDFAgent_ifce.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EMIRDFAGENT.idl
* lunes 18 de mayo de 2015 13H52' WEST
*/

public interface EMIRDFAgent_ifce extends EMIRDFAgent_ifceOperations, DFAGENT.DFAgent_ifce, org.omg.CORBA.portable.IDLEntity 
{
} // interface EMIRDFAgent_ifce
