// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:323


#include "EMIRDASC.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/Typecode.h"
#include "tao/Any_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"
#include "tao/Var_Size_Argument_T.h"
#include "ace/OS_NS_string.h"

#if defined (__BORLANDC__)
#pragma option -w-rvl -w-rch -w-ccc -w-aus -w-sig
#endif /* __BORLANDC__ */

#if !defined (__ACE_INLINE__)
#include "EMIRDASC.i"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:64

// Arg traits specializations.
namespace TAO
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:618

#if !defined (_DGT_TIMEVALUE__ARG_TRAITS_CS_)
#define _DGT_TIMEVALUE__ARG_TRAITS_CS_
  
  ACE_TEMPLATE_SPECIALIZATION
  class  Arg_Traits<DGT::TimeValue>
    : public
        Fixed_Size_Arg_Traits_T<
            DGT::TimeValue
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:379

#if !defined (_MONITOR_DATABLOCKLIST__ARG_TRAITS_CS_)
#define _MONITOR_DATABLOCKLIST__ARG_TRAITS_CS_
  
  ACE_TEMPLATE_SPECIALIZATION
  class  Arg_Traits<MONITOR::DataBlockList>
    : public
        Var_Size_Arg_Traits_T<
            MONITOR::DataBlockList,
            MONITOR::DataBlockList_var,
            MONITOR::DataBlockList_out
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:379

#if !defined (_MONITOR_STATECHANGELIST__ARG_TRAITS_CS_)
#define _MONITOR_STATECHANGELIST__ARG_TRAITS_CS_
  
  ACE_TEMPLATE_SPECIALIZATION
  class  Arg_Traits<MONITOR::StateChangeList>
    : public
        Var_Size_Arg_Traits_T<
            MONITOR::StateChangeList,
            MONITOR::StateChangeList_var,
            MONITOR::StateChangeList_out
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:379

#if !defined (_MONITOR_MAGNITUDECHANGELIST__ARG_TRAITS_CS_)
#define _MONITOR_MAGNITUDECHANGELIST__ARG_TRAITS_CS_
  
  ACE_TEMPLATE_SPECIALIZATION
  class  Arg_Traits<MONITOR::MagnitudeChangeList>
    : public
        Var_Size_Arg_Traits_T<
            MONITOR::MagnitudeChangeList,
            MONITOR::MagnitudeChangeList_var,
            MONITOR::MagnitudeChangeList_out
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:379

#if !defined (_CONFIG_PROPERTYCHANGELIST__ARG_TRAITS_CS_)
#define _CONFIG_PROPERTYCHANGELIST__ARG_TRAITS_CS_
  
  ACE_TEMPLATE_SPECIALIZATION
  class  Arg_Traits<CONFIG::PropertyChangeList>
    : public
        Var_Size_Arg_Traits_T<
            CONFIG::PropertyChangeList,
            CONFIG::PropertyChangeList_var,
            CONFIG::PropertyChangeList_out
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:537

#if !defined (_EMIRTYPES_READOUTMODE__ARG_TRAITS_CS_)
#define _EMIRTYPES_READOUTMODE__ARG_TRAITS_CS_
  
  ACE_TEMPLATE_SPECIALIZATION
  class  Arg_Traits<EMIRTYPES::ReadoutMode>
    : public
        Basic_Arg_Traits_T<
            EMIRTYPES::ReadoutMode
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:537

#if !defined (_EMIRTYPES_SDSUCONTROLLERSTATUS__ARG_TRAITS_CS_)
#define _EMIRTYPES_SDSUCONTROLLERSTATUS__ARG_TRAITS_CS_
  
  ACE_TEMPLATE_SPECIALIZATION
  class  Arg_Traits<EMIRTYPES::SDSUControllerStatus>
    : public
        Basic_Arg_Traits_T<
            EMIRTYPES::SDSUControllerStatus
          >
  {
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_arg_traits.cpp:618

#if !defined (_EMIRTYPES_ACQUISITIONCONFIGURATION__ARG_TRAITS_CS_)
#define _EMIRTYPES_ACQUISITIONCONFIGURATION__ARG_TRAITS_CS_
  
  ACE_TEMPLATE_SPECIALIZATION
  class  Arg_Traits<EMIRTYPES::AcquisitionConfiguration>
    : public
        Var_Size_Arg_Traits_T<
            EMIRTYPES::AcquisitionConfiguration,
            EMIRTYPES::AcquisitionConfiguration_var,
            EMIRTYPES::AcquisitionConfiguration_out
          >
  {
  };

#endif /* end #if !defined */
}


// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for EMIRDAS::EMIRDas_ifce.

ACE_TEMPLATE_CLASS_MEMBER_SPECIALIZATION
EMIRDAS::EMIRDas_ifce_ptr
TAO::Objref_Traits<EMIRDAS::EMIRDas_ifce>::tao_duplicate (
    EMIRDAS::EMIRDas_ifce_ptr p
  )
{
  return EMIRDAS::EMIRDas_ifce::_duplicate (p);
}

ACE_TEMPLATE_CLASS_MEMBER_SPECIALIZATION
void
TAO::Objref_Traits<EMIRDAS::EMIRDas_ifce>::tao_release (
    EMIRDAS::EMIRDas_ifce_ptr p
  )
{
  CORBA::release (p);
}

ACE_TEMPLATE_CLASS_MEMBER_SPECIALIZATION
EMIRDAS::EMIRDas_ifce_ptr
TAO::Objref_Traits<EMIRDAS::EMIRDas_ifce>::tao_nil (void)
{
  return EMIRDAS::EMIRDas_ifce::_nil ();
}

ACE_TEMPLATE_CLASS_MEMBER_SPECIALIZATION
CORBA::Boolean
TAO::Objref_Traits<EMIRDAS::EMIRDas_ifce>::tao_marshal (
    EMIRDAS::EMIRDas_ifce_ptr p,
    TAO_OutputCDR & cdr
  )
{
  return p->marshal (cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*EMIRDAS__TAO_EMIRDas_ifce_Proxy_Broker_Factory_function_pointer) (
    CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupDetector (
    const EMIRTYPES::AcquisitionConfiguration & acquisitionConfiguration
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<EMIRTYPES::AcquisitionConfiguration>::in_arg_val _tao_acquisitionConfiguration (acquisitionConfiguration);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_acquisitionConfiguration
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupDetector_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupDetector",
      13,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupDetector_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::expose (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_expose_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "expose",
      6,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_expose_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupReadoutMode (
    EMIRTYPES::ReadoutMode readoutmodeval
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<EMIRTYPES::ReadoutMode>::in_arg_val _tao_readoutmodeval (readoutmodeval);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_readoutmodeval
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupReadoutMode_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupReadoutMode",
      16,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupReadoutMode_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupImageTitle (
    const char * exposureId
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Char *>::in_arg_val _tao_exposureId (exposureId);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_exposureId
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupImageTitle_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupImageTitle",
      15,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupImageTitle_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupExposureTime (
    CORBA::Long exposureTime
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_exposureTime (exposureTime);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_exposureTime
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupExposureTime_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupExposureTime",
      17,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupExposureTime_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupWindowMode (
    CORBA::Boolean windowmode
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<ACE_InputCDR::to_boolean>::in_arg_val _tao_windowmode (windowmode);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_windowmode
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupWindowMode_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupWindowMode",
      15,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupWindowMode_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupNSEC (
    CORBA::Long nsec
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_nsec (nsec);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_nsec
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupNSEC_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupNSEC",
      9,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupNSEC_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupNO_EXPOSURES (
    CORBA::Long nexp
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_nexp (nexp);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_nexp
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupNO_EXPOSURES_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupNO_EXPOSURES",
      17,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupNO_EXPOSURES_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupNRDBL (
    CORBA::Long nrdbl
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_nrdbl (nrdbl);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_nrdbl
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupNRDBL_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupNRDBL",
      10,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupNRDBL_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupNRDBL_ND (
    CORBA::Long nrdbl_nd
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_nrdbl_nd (nrdbl_nd);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_nrdbl_nd
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupNRDBL_ND_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupNRDBL_ND",
      13,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupNRDBL_ND_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupNRST (
    CORBA::Long nrst
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_nrst (nrst);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_nrst
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupNRST_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupNRST",
      9,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupNRST_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupNPARAM_X (
    CORBA::Long nparam_x
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_nparam_x (nparam_x);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_nparam_x
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupNPARAM_X_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupNPARAM_X",
      13,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupNPARAM_X_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupNRDIL (
    CORBA::Long nrdil
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_nrdil (nrdil);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_nrdil
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupNRDIL_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupNRDIL",
      10,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupNRDIL_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupNRDIL_ND (
    CORBA::Long nrdil_nd
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_nrdil_nd (nrdil_nd);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_nrdil_nd
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupNRDIL_ND_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupNRDIL_ND",
      13,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupNRDIL_ND_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupOPTRST (
    CORBA::Long optrst
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_optrst (optrst);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_optrst
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupOPTRST_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupOPTRST",
      11,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupOPTRST_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupX_SIZE (
    CORBA::Long x_size
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_x_size (x_size);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_x_size
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupX_SIZE_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupX_SIZE",
      11,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupX_SIZE_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupY_SIZE (
    CORBA::Long y_size
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_y_size (y_size);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_y_size
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupY_SIZE_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupY_SIZE",
      11,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupY_SIZE_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::setupY_SIZE_B (
    CORBA::Long y_size_b
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
    , DGT::GCSException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Long>::in_arg_val _tao_y_size_b (y_size_b);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_y_size_b
    };
  
  static TAO::Exception_Data
  _tao_EMIRDAS_EMIRDas_ifce_setupY_SIZE_B_exceptiondata [] = 
    {
      {
        "IDL:gtc/DGT/GCSException:1.0",
        DGT::GCSException::_alloc,
        DGT::_tc_GCSException
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "setupY_SIZE_B",
      13,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_EMIRDAS_EMIRDas_ifce_setupY_SIZE_B_exceptiondata,
      1
      ACE_ENV_ARG_PARAMETER
    );
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Boolean EMIRDAS::EMIRDas_ifce::isSettingup (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<ACE_InputCDR::to_boolean>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_isSettingup",
      16,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Boolean EMIRDAS::EMIRDas_ifce::isConfigurationDone (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<ACE_InputCDR::to_boolean>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_isConfigurationDone",
      24,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Boolean EMIRDAS::EMIRDas_ifce::isExposing (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<ACE_InputCDR::to_boolean>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_isExposing",
      15,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Boolean EMIRDAS::EMIRDas_ifce::isDetectorControllerIdle (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<ACE_InputCDR::to_boolean>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_isDetectorControllerIdle",
      29,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::EMIRTYPES::ReadoutMode EMIRDAS::EMIRDas_ifce::currentReadoutMode (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<EMIRTYPES::ReadoutMode>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentReadoutMode",
      23,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

::EMIRTYPES::SDSUControllerStatus EMIRDAS::EMIRDas_ifce::currentSDSUControllerStatus (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<EMIRTYPES::SDSUControllerStatus>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentSDSUControllerStatus",
      32,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentElapsedTime (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentElapsedTime",
      23,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentExposureTime (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentExposureTime",
      24,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentNumberOfImages (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentNumberOfImages",
      26,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentNSEC (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentNSEC",
      16,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentNO_EXPOSURES (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentNO_EXPOSURES",
      24,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentNRDBL (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentNRDBL",
      17,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentNRDBL_ND (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentNRDBL_ND",
      20,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentNPARAM_X (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentNPARAM_X",
      20,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentNRST (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentNRST",
      16,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentNRDIL (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentNRDIL",
      17,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentNRDIL_ND (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentNRDIL_ND",
      20,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentOPTRST (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentOPTRST",
      18,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentX_SIZE (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentX_SIZE",
      18,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentY_SIZE (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentY_SIZE",
      18,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

CORBA::Long EMIRDAS::EMIRDas_ifce::currentY_SIZE_B (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Long>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_currentY_SIZE_B",
      20,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

char * EMIRDAS::EMIRDas_ifce::poweronApp (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Char *>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_poweronApp",
      15,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::poweronApp (
    const char * poweronApp
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Char *>::in_arg_val _tao_poweronApp (poweronApp);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_poweronApp
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "_set_poweronApp",
      15,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

char * EMIRDAS::EMIRDas_ifce::poweroffApp (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Char *>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_poweroffApp",
      16,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::poweroffApp (
    const char * poweroffApp
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Char *>::in_arg_val _tao_poweroffApp (poweroffApp);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_poweroffApp
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "_set_poweroffApp",
      16,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

char * EMIRDAS::EMIRDas_ifce::adqApp (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Char *>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_adqApp",
      11,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::adqApp (
    const char * adqApp
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Char *>::in_arg_val _tao_adqApp (adqApp);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_adqApp
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "_set_adqApp",
      11,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK;
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

char * EMIRDAS::EMIRDas_ifce::imgDir (
    ACE_ENV_SINGLE_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<CORBA::Char *>::ret_val _tao_retval;
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      1,
      "_get_imgDir",
      11,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK_RETURN (_tao_retval.excp ());
  
  return _tao_retval.retn ();
}

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void EMIRDAS::EMIRDas_ifce::imgDir (
    const char * imgDir
    ACE_ENV_ARG_DECL
  )
  ACE_THROW_SPEC ((
    CORBA::SystemException
  ))
{
  if (!this->is_evaluated ())
    {
      ACE_NESTED_CLASS (CORBA, Object)::tao_object_initialize (this);
    }
  
  if (this->the_TAO_EMIRDas_ifce_Proxy_Broker_ == 0)
    {
      EMIRDAS_EMIRDas_ifce_setup_collocation (
          this->ACE_NESTED_CLASS (CORBA, Object)::_is_collocated ()
        );
    }
  
  TAO::Arg_Traits<void>::ret_val _tao_retval;
  TAO::Arg_Traits<CORBA::Char *>::in_arg_val _tao_imgDir (imgDir);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_imgDir
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "_set_imgDir",
      11,
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_
    );
  
  _tao_call.invoke (0, 0 ACE_ENV_ARG_PARAMETER);
  ACE_CHECK;
}

EMIRDAS::EMIRDas_ifce::EMIRDas_ifce (int collocated)
 : the_TAO_EMIRDas_ifce_Proxy_Broker_ (0)
{
  this->EMIRDAS_EMIRDas_ifce_setup_collocation (collocated);
}

void
EMIRDAS::EMIRDas_ifce::EMIRDAS_EMIRDas_ifce_setup_collocation (int collocated)
{
  if (collocated)
    {
      this->the_TAO_EMIRDas_ifce_Proxy_Broker_ =
        ::EMIRDAS__TAO_EMIRDas_ifce_Proxy_Broker_Factory_function_pointer (this);
    }
  
  this->DCF_Device_ifce_setup_collocation (collocated);
}

EMIRDAS::EMIRDas_ifce::~EMIRDas_ifce (void)
{}

void 
EMIRDAS::EMIRDas_ifce::_tao_any_destructor (void *_tao_void_pointer)
{
  EMIRDas_ifce *_tao_tmp_pointer =
    ACE_static_cast (EMIRDas_ifce *, _tao_void_pointer);
  CORBA::release (_tao_tmp_pointer);
}

EMIRDAS::EMIRDas_ifce_ptr
EMIRDAS::EMIRDas_ifce::_narrow (
    CORBA::Object_ptr _tao_objref
    ACE_ENV_ARG_DECL
  )
{
  return
    TAO::Narrow_Utils<EMIRDas_ifce>::narrow (
        _tao_objref,
        "IDL:gtc/EMIRDAS/EMIRDas_ifce:1.0",
        EMIRDAS__TAO_EMIRDas_ifce_Proxy_Broker_Factory_function_pointer
        ACE_ENV_ARG_PARAMETER
      );
}

EMIRDAS::EMIRDas_ifce_ptr
EMIRDAS::EMIRDas_ifce::_unchecked_narrow (
    CORBA::Object_ptr _tao_objref
    ACE_ENV_ARG_DECL
  )
{
  return
    TAO::Narrow_Utils<EMIRDas_ifce>::unchecked_narrow (
        _tao_objref,
        "IDL:gtc/EMIRDAS/EMIRDas_ifce:1.0",
        EMIRDAS__TAO_EMIRDas_ifce_Proxy_Broker_Factory_function_pointer
        ACE_ENV_ARG_PARAMETER
      );
}

EMIRDAS::EMIRDas_ifce_ptr
EMIRDAS::EMIRDas_ifce::_duplicate (EMIRDas_ifce_ptr obj)
{
  if (! CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

CORBA::Boolean
EMIRDAS::EMIRDas_ifce::_is_a (
    const char *value
    ACE_ENV_ARG_DECL
  )
{
  if (
      !ACE_OS::strcmp (
          (char *)value,
          "IDL:gtc/DCF/Device_ifce:1.0"
        ) ||
      !ACE_OS::strcmp (
          (char *)value,
          "IDL:gtc/EMIRDAS/EMIRDas_ifce:1.0"
        ) ||
      !ACE_OS::strcmp (
          (char *)value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
     )
    {
      return 1; // success using local knowledge
    }
  else
    {
      return this->ACE_NESTED_CLASS (CORBA, Object)::_is_a (
          value
          ACE_ENV_ARG_PARAMETER
        );
    }
}

const char* EMIRDAS::EMIRDas_ifce::_interface_repository_id (void) const
{
  return "IDL:gtc/EMIRDAS/EMIRDas_ifce:1.0";
}

CORBA::Boolean
EMIRDAS::EMIRDas_ifce::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/typecode_defn.cpp:284

static const CORBA::Long _oc_EMIRDAS_EMIRDas_ifce[] =
{
    TAO_ENCAP_BYTE_ORDER, // byte order
  33,
  ACE_NTOHL (0x49444c3a), 
  ACE_NTOHL (0x6774632f), 
  ACE_NTOHL (0x454d4952), 
  ACE_NTOHL (0x4441532f), 
  ACE_NTOHL (0x454d4952), 
  ACE_NTOHL (0x4461735f), 
  ACE_NTOHL (0x69666365), 
  ACE_NTOHL (0x3a312e30), 
  ACE_NTOHL (0x0),  // repository ID = IDL:gtc/EMIRDAS/EMIRDas_ifce:1.0
    13,
  ACE_NTOHL (0x454d4952), 
  ACE_NTOHL (0x4461735f), 
  ACE_NTOHL (0x69666365), 
  ACE_NTOHL (0x0),  // name = EMIRDas_ifce
  };

static CORBA::TypeCode _tc_TAO_tc_EMIRDAS_EMIRDas_ifce (
    CORBA::tk_objref,
    sizeof (_oc_EMIRDAS_EMIRDas_ifce),
    (char *) &_oc_EMIRDAS_EMIRDas_ifce,
    0,
    sizeof (EMIRDAS::EMIRDas_ifce)
  );

namespace EMIRDAS
{
  ::CORBA::TypeCode_ptr _tc_EMIRDas_ifce =
    &_tc_TAO_tc_EMIRDAS_EMIRDas_ifce;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:50

ACE_TEMPLATE_SPECIALIZATION
CORBA::Boolean
TAO::Any_Impl_T<EMIRDAS::EMIRDas_ifce>::to_object (
    CORBA::Object_ptr &_tao_elem
  ) const
{
  _tao_elem = CORBA::Object::_duplicate (this->value_);
  return 1;
}

// Copying insertion.
void
operator<<= (
    CORBA::Any &_tao_any,
    EMIRDAS::EMIRDas_ifce_ptr _tao_elem
  )
{
  EMIRDAS::EMIRDas_ifce_ptr _tao_objptr =
    EMIRDAS::EMIRDas_ifce::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

// Non-copying insertion.
void
operator<<= (
    CORBA::Any &_tao_any,
    EMIRDAS::EMIRDas_ifce_ptr *_tao_elem
  )
{
  TAO::Any_Impl_T<EMIRDAS::EMIRDas_ifce>::insert (
      _tao_any,
      EMIRDAS::EMIRDas_ifce::_tao_any_destructor,
      EMIRDAS::_tc_EMIRDas_ifce,
      *_tao_elem
    );
}

CORBA::Boolean
operator>>= (
    const CORBA::Any &_tao_any,
    EMIRDAS::EMIRDas_ifce_ptr &_tao_elem
  )
{
  return
    TAO::Any_Impl_T<EMIRDAS::EMIRDas_ifce>::extract (
        _tao_any,
        EMIRDAS::EMIRDas_ifce::_tao_any_destructor,
        EMIRDAS::_tc_EMIRDas_ifce,
        _tao_elem
      );
}

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const EMIRDAS::EMIRDas_ifce_ptr _tao_objref
  )
{
  CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    EMIRDAS::EMIRDas_ifce_ptr &_tao_objref
  )
{
  CORBA::Object_var obj;
  
  if ((strm >> obj.inout ()) == 0)
    {
      return 0;
    }
  
  typedef ::EMIRDAS::EMIRDas_ifce RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        EMIRDAS__TAO_EMIRDas_ifce_Proxy_Broker_Factory_function_pointer
      );
    
  return 1;
}

