package EMIRDFAGENT;

/**
* EMIRDFAGENT/EMIRDFAgent_ifceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EMIRDFAGENT.idl
* lunes 18 de mayo de 2015 13H54' WEST
*/

public final class EMIRDFAgent_ifceHolder implements org.omg.CORBA.portable.Streamable
{
  public EMIRDFAGENT.EMIRDFAgent_ifce value = null;

  public EMIRDFAgent_ifceHolder ()
  {
  }

  public EMIRDFAgent_ifceHolder (EMIRDFAGENT.EMIRDFAgent_ifce initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EMIRDFAGENT.EMIRDFAgent_ifceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EMIRDFAGENT.EMIRDFAgent_ifceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EMIRDFAGENT.EMIRDFAgent_ifceHelper.type ();
  }

}
