package EMIRTYPES;


/**
* EMIRTYPES/AcquisitionConfiguration.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EMIRTYPES.idl
* lunes 18 de mayo de 2015 13H54' WEST
*/

public final class AcquisitionConfiguration implements org.omg.CORBA.portable.IDLEntity
{
  public String title = null;
  public EMIRTYPES.ReadoutMode readoutmodeval = null;
  public int exposuretime = (int)0;
  public int x_size = (int)0;
  public int y_size = (int)0;
  public boolean windowMode = false;
  public boolean applyConfiguration = false;
  public boolean applySimulateImage = false;
  public boolean saveImages = false;
  public int nsec = (int)0;

  // Number of sequences in an observation
  public int optrst = (int)0;

  // Type of detector resets to be performed
  public int nrst = (int)0;

  // Number of detector resets
  public int nrdbl = (int)0;

  // Number of detector resets before loop
  public int nrdbl_nd = (int)0;

  // Detectors resets before the loop with no data
  public int numExp = (int)0;

  // Number of expositions per sequence
  public int nrdil = (int)0;

  // Number of detector resets inside the loop
  public int nrdil_nd = (int)0;

  // Detector resets inside the loop with no data
  public int nparam_x = (int)0;

  public AcquisitionConfiguration ()
  {
  } // ctor

  public AcquisitionConfiguration (String _title, EMIRTYPES.ReadoutMode _readoutmodeval, int _exposuretime, int _x_size, int _y_size, boolean _windowMode, boolean _applyConfiguration, boolean _applySimulateImage, boolean _saveImages, int _nsec, int _optrst, int _nrst, int _nrdbl, int _nrdbl_nd, int _numExp, int _nrdil, int _nrdil_nd, int _nparam_x)
  {
    title = _title;
    readoutmodeval = _readoutmodeval;
    exposuretime = _exposuretime;
    x_size = _x_size;
    y_size = _y_size;
    windowMode = _windowMode;
    applyConfiguration = _applyConfiguration;
    applySimulateImage = _applySimulateImage;
    saveImages = _saveImages;
    nsec = _nsec;
    optrst = _optrst;
    nrst = _nrst;
    nrdbl = _nrdbl;
    nrdbl_nd = _nrdbl_nd;
    numExp = _numExp;
    nrdil = _nrdil;
    nrdil_nd = _nrdil_nd;
    nparam_x = _nparam_x;
  } // ctor

} // class AcquisitionConfiguration
