package EMIRTYPES;


/**
* EMIRTYPES/ParamListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EMIRTYPES.idl
* lunes 18 de mayo de 2015 13H54' WEST
*/

public final class ParamListHolder implements org.omg.CORBA.portable.Streamable
{
  public EMIRTYPES.NameValue value[] = null;

  public ParamListHolder ()
  {
  }

  public ParamListHolder (EMIRTYPES.NameValue[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EMIRTYPES.ParamListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EMIRTYPES.ParamListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EMIRTYPES.ParamListHelper.type ();
  }

}
