package EMIRTYPES;

/**
* EMIRTYPES/ReadoutModeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EMIRTYPES.idl
* lunes 18 de mayo de 2015 13H54' WEST
*/

public final class ReadoutModeHolder implements org.omg.CORBA.portable.Streamable
{
  public EMIRTYPES.ReadoutMode value = null;

  public ReadoutModeHolder ()
  {
  }

  public ReadoutModeHolder (EMIRTYPES.ReadoutMode initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EMIRTYPES.ReadoutModeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EMIRTYPES.ReadoutModeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EMIRTYPES.ReadoutModeHelper.type ();
  }

}
