package EMIRTYPES;


/**
* EMIRTYPES/SDSUControllerStatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EMIRTYPES.idl
* lunes 18 de mayo de 2015 13H54' WEST
*/

abstract public class SDSUControllerStatusHelper
{
  private static String  _id = "IDL:gtc/EMIRTYPES/SDSUControllerStatus:1.0";

  public static void insert (org.omg.CORBA.Any a, EMIRTYPES.SDSUControllerStatus that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EMIRTYPES.SDSUControllerStatus extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (EMIRTYPES.SDSUControllerStatusHelper.id (), "SDSUControllerStatus", new String[] { "DETECTOR_IDLE", "DETECTOR_ERROR", "DETECTOR_RUNNING", "DETECTOR_ENDS"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EMIRTYPES.SDSUControllerStatus read (org.omg.CORBA.portable.InputStream istream)
  {
    return EMIRTYPES.SDSUControllerStatus.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EMIRTYPES.SDSUControllerStatus value)
  {
    ostream.write_long (value.value ());
  }

}
