package EMIRTYPES;


/**
* EMIRTYPES/SDSUControllerStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EMIRTYPES.idl
* lunes 18 de mayo de 2015 13H54' WEST
*/

public class SDSUControllerStatus implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static EMIRTYPES.SDSUControllerStatus[] __array = new EMIRTYPES.SDSUControllerStatus [__size];

  public static final int _DETECTOR_IDLE = 0;
  public static final EMIRTYPES.SDSUControllerStatus DETECTOR_IDLE = new EMIRTYPES.SDSUControllerStatus(_DETECTOR_IDLE);
  public static final int _DETECTOR_ERROR = 1;
  public static final EMIRTYPES.SDSUControllerStatus DETECTOR_ERROR = new EMIRTYPES.SDSUControllerStatus(_DETECTOR_ERROR);
  public static final int _DETECTOR_RUNNING = 2;
  public static final EMIRTYPES.SDSUControllerStatus DETECTOR_RUNNING = new EMIRTYPES.SDSUControllerStatus(_DETECTOR_RUNNING);
  public static final int _DETECTOR_ENDS = 3;
  public static final EMIRTYPES.SDSUControllerStatus DETECTOR_ENDS = new EMIRTYPES.SDSUControllerStatus(_DETECTOR_ENDS);

  public int value ()
  {
    return __value;
  }

  public static EMIRTYPES.SDSUControllerStatus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected SDSUControllerStatus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class SDSUControllerStatus
