package EMIRTYPES;

/**
* EMIRTYPES/SDSUControllerStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EMIRTYPES.idl
* lunes 18 de mayo de 2015 13H54' WEST
*/

public final class SDSUControllerStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public EMIRTYPES.SDSUControllerStatus value = null;

  public SDSUControllerStatusHolder ()
  {
  }

  public SDSUControllerStatusHolder (EMIRTYPES.SDSUControllerStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = EMIRTYPES.SDSUControllerStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    EMIRTYPES.SDSUControllerStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return EMIRTYPES.SDSUControllerStatusHelper.type ();
  }

}
