// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:171

#ifndef _TAO_IDL_IDLC___EMIRTYPESC_H_
#define _TAO_IDL_IDLC___EMIRTYPESC_H_

#include "tao/ORB.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

#include "tao/CDR.h"
#include "tao/Environment.h"
#include "tao/Any.h"
#include "tao/Sequence_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/VarOut_T.h"

#include "DGTC.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

#if defined (TAO_EXPORT_NESTED_CLASSES)
#  if defined (TAO_EXPORT_NESTED_MACRO)
#    undef TAO_EXPORT_NESTED_MACRO
#  endif /* defined (TAO_EXPORT_NESTED_MACRO) */
#  define TAO_EXPORT_NESTED_MACRO 
#endif /* TAO_EXPORT_NESTED_CLASSES */

#if defined(_MSC_VER)
#if (_MSC_VER >= 1200)
#pragma warning(push)
#endif /* _MSC_VER >= 1200 */
#pragma warning(disable:4250)
#endif /* _MSC_VER */

#if defined (__BORLANDC__)
#pragma option push -w-rvl -w-rch -w-ccc -w-inl
#endif /* __BORLANDC__ */

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:48

namespace EMIRTYPES
{
  
  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:57
  
  enum ReadoutMode
  {
    SINGLE,
    CDS,
    FOWLER,
    RAMP,
    HDR_SIMPLE,
    BIAS,
    MRAMP,
    UNDEFINED
  };
  
  typedef ReadoutMode &ReadoutMode_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:44
  
  TAO_NAMESPACE_STORAGE_CLASS ::CORBA::TypeCode_ptr _tc_ReadoutMode;
  
  // TAO_IDL - Generated from
  // be/be_visitor_enum/enum_ch.cpp:57
  
  enum SDSUControllerStatus
  {
    DETECTOR_IDLE,
    DETECTOR_ERROR,
    DETECTOR_RUNNING,
    DETECTOR_ENDS
  };
  
  typedef SDSUControllerStatus &SDSUControllerStatus_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:44
  
  TAO_NAMESPACE_STORAGE_CLASS ::CORBA::TypeCode_ptr _tc_SDSUControllerStatus;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:258
  
  struct NameValue;
  
  typedef
    TAO_Var_Var_T<
        NameValue
      >
    NameValue_var;
  
  typedef
    TAO_Out_T<
        NameValue,
        NameValue_var
      >
    NameValue_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:52
  
  struct  NameValue
  {
    typedef NameValue_var _var_type;
    
    static void _tao_any_destructor (void *);
    TAO_String_Manager name;
    CORBA::Any value;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:44
  
  TAO_NAMESPACE_STORAGE_CLASS ::CORBA::TypeCode_ptr _tc_NameValue;
  
  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:101

#if !defined (_EMIRTYPES_PARAMLIST_CH_)
#define _EMIRTYPES_PARAMLIST_CH_
  
  class ParamList;
  
  typedef
    TAO_VarSeq_Var_T<
        ParamList,
        NameValue
      >
    ParamList_var;
  
  typedef
    TAO_Seq_Out_T<
        ParamList,
        ParamList_var,
        NameValue
      >
    ParamList_out;
  
  class  ParamList
    : public
        TAO_Unbounded_Sequence<
            NameValue
          >
  {
  public:
    ParamList (void);
    ParamList (CORBA::ULong max);
    ParamList (
        CORBA::ULong max,
        CORBA::ULong length,
        NameValue* buffer, 
        CORBA::Boolean release = 0
      );
    ParamList (const ParamList &);
    ~ParamList (void);
    
    static void _tao_any_destructor (void *);
    
    typedef ParamList_var _var_type;
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:44
  
  TAO_NAMESPACE_STORAGE_CLASS ::CORBA::TypeCode_ptr _tc_ParamList;
  
  // TAO_IDL - Generated from
  // be/be_type.cpp:258
  
  struct AcquisitionConfiguration;
  
  typedef
    TAO_Var_Var_T<
        AcquisitionConfiguration
      >
    AcquisitionConfiguration_var;
  
  typedef
    TAO_Out_T<
        AcquisitionConfiguration,
        AcquisitionConfiguration_var
      >
    AcquisitionConfiguration_out;
  
  // TAO_IDL - Generated from
  // be/be_visitor_structure/structure_ch.cpp:52
  
  struct  AcquisitionConfiguration
  {
    typedef AcquisitionConfiguration_var _var_type;
    
    static void _tao_any_destructor (void *);
    TAO_String_Manager title;
    EMIRTYPES::ReadoutMode readoutmodeval;
    CORBA::Long exposuretime;
    CORBA::Long x_size;
    CORBA::Long y_size;
    CORBA::Boolean windowMode;
    CORBA::Boolean applyConfiguration;
    CORBA::Boolean applySimulateImage;
    CORBA::Boolean saveImages;
    CORBA::Long nsec;
    CORBA::Long optrst;
    CORBA::Long nrst;
    CORBA::Long nrdbl;
    CORBA::Long nrdbl_nd;
    CORBA::Long numExp;
    CORBA::Long nrdil;
    CORBA::Long nrdil_nd;
    CORBA::Long nparam_x;
  };
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:44
  
  TAO_NAMESPACE_STORAGE_CLASS ::CORBA::TypeCode_ptr _tc_AcquisitionConfiguration;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:66

} // module EMIRTYPES

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:59

// Traits specializations.
namespace TAO
{
}

// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:51

 void operator<<= (CORBA::Any &, EMIRTYPES::ReadoutMode);
 CORBA::Boolean operator>>= (const CORBA::Any &, EMIRTYPES::ReadoutMode &);

// TAO_IDL - Generated from
// be/be_visitor_enum/any_op_ch.cpp:51

 void operator<<= (CORBA::Any &, EMIRTYPES::SDSUControllerStatus);
 CORBA::Boolean operator>>= (const CORBA::Any &, EMIRTYPES::SDSUControllerStatus &);

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:52

 void operator<<= (CORBA::Any &, const EMIRTYPES::NameValue &); // copying version
 void operator<<= (CORBA::Any &, EMIRTYPES::NameValue*); // noncopying version
 CORBA::Boolean operator>>= (const CORBA::Any &, EMIRTYPES::NameValue *&); // deprecated
 CORBA::Boolean operator>>= (const CORBA::Any &, const EMIRTYPES::NameValue *&);

// TAO_IDL - Generated from
// be/be_visitor_sequence/any_op_ch.cpp:52

 void operator<<= (CORBA::Any &, const EMIRTYPES::ParamList &); // copying version
 void operator<<= (CORBA::Any &, EMIRTYPES::ParamList*); // noncopying version
 CORBA::Boolean operator>>= (const CORBA::Any &, EMIRTYPES::ParamList *&); // deprecated
 CORBA::Boolean operator>>= (const CORBA::Any &, const EMIRTYPES::ParamList *&);

// TAO_IDL - Generated from
// be/be_visitor_structure/any_op_ch.cpp:52

 void operator<<= (CORBA::Any &, const EMIRTYPES::AcquisitionConfiguration &); // copying version
 void operator<<= (CORBA::Any &, EMIRTYPES::AcquisitionConfiguration*); // noncopying version
 CORBA::Boolean operator>>= (const CORBA::Any &, EMIRTYPES::AcquisitionConfiguration *&); // deprecated
 CORBA::Boolean operator>>= (const CORBA::Any &, const EMIRTYPES::AcquisitionConfiguration *&);

// TAO_IDL - Generated from
// be/be_visitor_root/cdr_op.cpp:48

#ifndef __ACE_INLINE__

// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:50

 CORBA::Boolean operator<< (TAO_OutputCDR &, const EMIRTYPES::ReadoutMode &);
 CORBA::Boolean operator>> (TAO_InputCDR &, EMIRTYPES::ReadoutMode &);

// TAO_IDL - Generated from
// be/be_visitor_enum/cdr_op_ch.cpp:50

 CORBA::Boolean operator<< (TAO_OutputCDR &, const EMIRTYPES::SDSUControllerStatus &);
 CORBA::Boolean operator>> (TAO_InputCDR &, EMIRTYPES::SDSUControllerStatus &);

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:53

 CORBA::Boolean operator<< (TAO_OutputCDR &, const EMIRTYPES::NameValue &);
 CORBA::Boolean operator>> (TAO_InputCDR &, EMIRTYPES::NameValue &);

// TAO_IDL - Generated from
// be/be_visitor_sequence/cdr_op_ch.cpp:70

#if !defined _TAO_CDR_OP_EMIRTYPES_ParamList_H_
#define _TAO_CDR_OP_EMIRTYPES_ParamList_H_

 CORBA::Boolean operator<< (
    TAO_OutputCDR &,
    const EMIRTYPES::ParamList &
  );
 CORBA::Boolean operator>> (
    TAO_InputCDR &,
    EMIRTYPES::ParamList &
  );

#endif /* _TAO_CDR_OP_EMIRTYPES_ParamList_H_ */

// TAO_IDL - Generated from
// be/be_visitor_structure/cdr_op_ch.cpp:53

 CORBA::Boolean operator<< (TAO_OutputCDR &, const EMIRTYPES::AcquisitionConfiguration &);
 CORBA::Boolean operator>> (TAO_InputCDR &, EMIRTYPES::AcquisitionConfiguration &);

// TAO_IDL - Generated from
// be/be_visitor_root/cdr_op.cpp:64

#endif /* __ACE_INLINE__ */

// TAO_IDL - Generated from
// be/be_codegen.cpp:978

#if defined (__ACE_INLINE__)
#include "EMIRTYPESC.i"
#endif /* defined INLINE */

#if defined(_MSC_VER) && (_MSC_VER >= 1200)
#pragma warning(pop)
#endif /* _MSC_VER */

#if defined (__BORLANDC__)
#pragma option pop
#endif /* __BORLANDC__ */

#endif /* ifndef */

