package EMIRDAS;


/**
* EMIRDAS/EMIRDas_ifce.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EMIRDAS.idl
* lunes 18 de mayo de 2015 13H54' WEST
*/

public interface EMIRDas_ifce extends EMIRDas_ifceOperations, DCF.Device_ifce, org.omg.CORBA.portable.IDLEntity 
{
} // interface EMIRDas_ifce
