package EMIRDAS;


/**
* EMIRDAS/EMIRDas_ifceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from EMIRDAS.idl
* lunes 18 de mayo de 2015 13H54' WEST
*/

abstract public class EMIRDas_ifceHelper
{
  private static String  _id = "IDL:gtc/EMIRDAS/EMIRDas_ifce:1.0";

  public static void insert (org.omg.CORBA.Any a, EMIRDAS.EMIRDas_ifce that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static EMIRDAS.EMIRDas_ifce extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (EMIRDAS.EMIRDas_ifceHelper.id (), "EMIRDas_ifce");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static EMIRDAS.EMIRDas_ifce read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_EMIRDas_ifceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, EMIRDAS.EMIRDas_ifce value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static EMIRDAS.EMIRDas_ifce narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EMIRDAS.EMIRDas_ifce)
      return (EMIRDAS.EMIRDas_ifce)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EMIRDAS._EMIRDas_ifceStub stub = new EMIRDAS._EMIRDas_ifceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static EMIRDAS.EMIRDas_ifce unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof EMIRDAS.EMIRDas_ifce)
      return (EMIRDAS.EMIRDas_ifce)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      EMIRDAS._EMIRDas_ifceStub stub = new EMIRDAS._EMIRDas_ifceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
